import React from 'react';
import { Lightbulb, Tag, ArrowRight, BarChart2, CheckCircle, AlertTriangle } from 'lucide-react';

export default function AIInsights({ insights, topics, onTopicClick }) {
  if (!insights || !topics) return null;

  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
      
      {/* AI Insights Card (2 columns wide) */}
      <div className="lg:col-span-2 bg-gradient-to-br from-slate-900 via-indigo-950 to-slate-900 text-white rounded-2xl p-6 shadow-md border border-indigo-900/60 relative overflow-hidden flex flex-col justify-between">
        
        <div className="absolute top-0 right-0 w-64 h-64 bg-indigo-500/10 rounded-full blur-3xl pointer-events-none"></div>

        <div>
          <div className="flex items-center space-x-3 mb-4">
            <div className="p-2.5 rounded-xl bg-indigo-600/40 border border-indigo-500/30 text-indigo-300">
              <Lightbulb className="w-5 h-5 animate-pulse" />
            </div>
            <div>
              <h3 className="text-lg font-bold text-white">AI Executive Insights</h3>
              <p className="text-xs text-indigo-200/70">Automated feedback intelligence synthesis</p>
            </div>
          </div>

          <div className="space-y-3 mt-4">
            {insights.map((text, idx) => (
              <div key={idx} className="flex items-start space-x-3 text-xs sm:text-sm text-slate-200 leading-relaxed bg-white/5 p-3 rounded-xl border border-white/10">
                {text.includes('--- DEEP RISK') ? (
                  <AlertTriangle className="w-4 h-4 text-rose-400 shrink-0 mt-0.5" />
                ) : (
                  <CheckCircle className="w-4 h-4 text-indigo-400 shrink-0 mt-0.5" />
                )}
                <div 
                  className="whitespace-pre-wrap font-medium"
                  dangerouslySetInnerHTML={{ __html: text.replace(/\*\*(.*?)\*\*/g, '<span class="text-white font-bold">$1</span>') }}
                />
              </div>
            ))}
          </div>
        </div>

        <div className="mt-6 pt-4 border-t border-indigo-900/50 flex items-center justify-between text-xs text-indigo-300">
          <span>Generated by FeedSense AI NLP Engine</span>
          <span className="font-semibold text-emerald-400">100% Real-Time Analysis</span>
        </div>

      </div>

      {/* Common Topics Card (1 column wide) */}
      <div className="bg-white dark:bg-slate-900 rounded-2xl p-6 shadow-sm border border-slate-200 dark:border-slate-800 flex flex-col justify-between">
        <div>
          <div className="flex items-center space-x-3 mb-4">
            <div className="p-2 rounded-lg bg-amber-50 dark:bg-amber-950 text-amber-600 dark:text-amber-400">
              <Tag className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-base font-bold text-slate-900 dark:text-white">Common Topics</h3>
              <p className="text-xs text-slate-500 dark:text-slate-400">Click a topic to filter feedback results</p>
            </div>
          </div>

          <div className="space-y-2 mt-4">
            {topics.length > 0 ? (
              topics.map((t, idx) => (
                <button
                  key={idx}
                  onClick={() => onTopicClick(t.topic)}
                  className="w-full flex items-center justify-between p-2.5 rounded-xl bg-slate-50 dark:bg-slate-800/80 hover:bg-blue-50 dark:hover:bg-blue-950/50 border border-slate-200 dark:border-slate-700 hover:border-blue-300 transition-all text-xs group"
                >
                  <span className="font-semibold text-slate-700 dark:text-slate-200 group-hover:text-blue-600 dark:group-hover:text-blue-400">
                    #{t.topic}
                  </span>
                  <span className="px-2 py-0.5 rounded-full text-[11px] font-bold bg-slate-200 dark:bg-slate-700 text-slate-600 dark:text-slate-300 group-hover:bg-blue-100 dark:group-hover:bg-blue-900 group-hover:text-blue-700">
                    {t.count} entries
                  </span>
                </button>
              ))
            ) : (
              <p className="text-xs text-slate-400 py-4 text-center">No recurring topic keywords identified.</p>
            )}
          </div>
        </div>

        <p className="text-[11px] text-slate-400 dark:text-slate-500 mt-4 text-center">
          💡 Click any keyword badge to filter table results instantly.
        </p>
      </div>

    </div>
  );
}
